### ISSUE TITLE
About the EWTA loss

### ISSUE THREAD

**Issue by ynw2021** [lmb-freiburg/Contrastive-Future-Trajectory-Prediction#3]
Hi, Thanks for your great work!
I am wondering how do you make the parameter K in the ewta loss decay ,as there is no guidance in the config file you provided.
Looking forward to your reply and thank you in advance

**Comment by os1a** [comment]
Hi,

Thanks for your interest in our work.

Regarding your question: we do follow the same mechansim in decaying K as the original paper "Overcoming Limitations of Mixture Density Networks ....", where we start with penalizing all hypotheses K=20, and then after some time of training, we reduce K to its half K=10 and so on until we end up with K=1.

Hope that helps,

**Comment by ynw2021** [comment]
Thank you，that helps alot！
